project/recipes/views.py
from flask import render_template, Blueprint, flash, redirect, session, url_for, request

from flask_login import login_user, current_user, login_required, logout_user
from project import app, db ,admin, mail
from project.models import User, Recipe, Image, Category
from project.forms import NewRecipeForm,NewCategoryForm


recipes_bp = Blueprint('recipes',__name__)

@recipes_bp.route('/')
def index():
    return render_template('home.html')

@recipes_bp.route('/add',methods=['GET','POST'])
def add():
    form = NewRecipeForm()
    if form.validate_on_submit():
        if current_user.is_authenticated:
            recipe = Recipe(title=form.title.data,servings=form.servings.data,
                        cooking_time=form.cooking_time.data, difficulty=form.difficulty.data,
                        calories=form.calories.data, ingredients=form.ingredients.data,
                        method=form.method.data)
            for catid in form.categories.data:
                category = Category.query.get(catid)
                recipe.categories.append(category)
            user = User.query.get(form.user.data)
            recipe.user_id=user.id
            db.session.add(recipe)
            db.session.commit()
            flash('A new recipe has been added succesfuly!','success')
            return redirect('/recipes')
        else:
            flash('Error!Recipe was not added!',"danger")
            return redirect('/add')
    return render_template('add_recipe.html',
                            form = form)

@recipes_bp.route('/recipes',methods=['GET'])
def allRecipes():
    recipes=Recipe.query.all()
    return render_template('all_recipes.html',
                            title='All Recipes',
                            recipes=recipes)

@recipes_bp.route('/categories',methods=['GET'])
def categories():
    categories=Category.query.all()
    return render_template('categories.html',
                            title="All Categories",
                            categories=categories)


@recipes_bp.route('/categories/<id>',methods=['GET'])
def getRecipesByCategory(id):
    c = Category.query.filter_by(id=id).first()
    return render_template('categories.html',
                            title='Recipes in the category ' + str(c),
                            categories=c.recipes)

@recipes_bp.route('/add_category',methods=['GET','POST'])
def addCategory():
    form=NewCategoryForm()
    if form.validate_on_submit():
        if current_user.is_authenticated:
            category=Category(dish_type=form.dish_type.data)
            for recid in form.recipes.data:
                recipe = Recipe.query.get(recid)
                category.recipes.append(recipe)
            db.session.add(category)
            db.session.commit()
            flash('You have added a new category!','success')
            return redirect('/categories')
        else:
            flash('Error adding category!','danger')
            return redirect('/add_category')
    return render_template('add_category.html',
                            title='New Category',
                            form=form)

project/users/views.py
from flask import Blueprint, render_template, flash, redirect, session, url_for, request
from flask_admin.contrib.sqla import ModelView
from flask_login import login_user, current_user, login_required, logout_user
from flask_mail import Message

from sqlalchemy import exc

from project import app, db ,admin, mail
from project.models import User, Recipe, Image, Category
from project.forms import UserSignupForm, LoginUserForm, ResetPasswordReqForm, ResetPasswordForm, NewPasswordForm

admin.add_view(ModelView(User, db.session))
admin.add_view(ModelView(Recipe, db.session))
admin.add_view(ModelView(Image, db.session))
admin.add_view(ModelView(Category, db.session))

users_bp = Blueprint('users',__name__)

# helper functions
def send_email(subject, sender, recipients, text_body, html_body):
    message = Message(subject, sender=sender, recipients=recipients)
    message.body = text_body
    message.html = html_body
    mail.send(message)

def send_password_res_email(user):
    token = user.get_res_password_token()
    send_email('[Recipe Diary] Reset Your Password',
                sender=app.config['ADMINS'][0],
                recipients=[user.email],
                text_body=render_template('email/res_password.txt',
                                         user=user, token=token),
                html_body=render_template('email/res_password.html',
                                         user=user, token=token)
    )

# user routes
@users_bp.route('/signup',methods=['GET','POST'])
def sign_up():
    form = UserSignupForm()
    # flash('Errors="%s"'%(form.errors),"warning")
    if form.validate_on_submit():
        try:
            u = User(firstname=form.firstname.data, surname = form.surname.data, email = form.email.data)
            u.set_password(form.password.data)
            u.authenticated = True
            db.session.add(u)
            db.session.commit()

            message = Message(subject='[Recipe Diary] Registration',
                              body='Thank you for registering!',
                              recipients=[u.email])
            mail.send(message)
            flash("Thank you for signing up!","success")
            return redirect('/login')
        except exc.IntegrityError:
            db.session.rollback()
            flash("Error! Email ({}) already exists.".format(form.email.data),"danger")    
        return redirect('/signup')
    
    return render_template('sign_up.html',
                            title="Sign Up",
                            form = form)

@users_bp.route('/login',methods=['GET','POST'])
def login():
    form = LoginUserForm()
    if form.validate_on_submit():
        u = User.query.filter_by(email=form.email.data).first()
        if u is not None and u.check_password(form.password.data):
            u.authenticated = True
            db.session.add(u)
            db.session.commit()
            login_user(u)
            flash("Welcome back, {}!".format(current_user.firstname),"success")
            return redirect('/')
        else:
            flash("Please check your login details and try again","danger")
            return redirect('/login')

    return render_template('login.html',
                            title="Login",
                            form=form)

@users_bp.route('/logout')
@login_required
def logout():
    u = current_user
    u.authenticated = False
    db.session.add(u)
    db.session.commit()
    logout_user()
    flash("Goodbye!", "info")
    return redirect('/login')

@users_bp.route('/reset_password_req',methods=['GET','POST'])
def reset_password_req():
    if current_user.is_authenticated:
        return redirect('/')
    form = ResetPasswordReqForm()
    if form.validate_on_submit():
        u = User.query.filter_by(email=form.email.data).first()
        if u:
            send_password_res_email(u)
        flash('Check your email for password reset instructions','info')
        return redirect('/login')
    return render_template('reset_password_req.html',
                            title='Reset Password',
                            form=form)
    
@users_bp.route('/reset_password/<token>', methods=['GET','POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect('/')
    u = User.verify_token(token)
    if not u:
        return redirect('/')
    form = ResetPasswordForm()
    if form.validate_on_submit():
        u.set_password(form.password.data)
        db.session.commit()
        flash('Your password has been reset.','info')
        return redirect('/login')
    return render_template('reset_password.html', form=form)

@users_bp.route('/profile',methods=['GET'])
def profile():
    if current_user.is_authenticated:
        return render_template('user_profile.html',
                                title='My Profile')

@users_bp.route('/change_password', methods=["GET","POST"])
@login_required
def change_password():
    form = NewPasswordForm()
    if form.validate_on_submit():
        user = current_user
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Password has been updated successfuly!', 'success')
        return redirect('/profile')
    return render_template('change_password.html', form=form)

project/templates/add_category.html
<!-- extend base layoout -->
{% extends "base.html" %}

{% block content %}

    <h1 class='text-center mb-3'>Add New Category</h1>
            <form action="" method="POST">
            {{form.hidden_tag() }}
            <p>
            Dish Type: {{ form.dish_type(class_='form-control')}}<br>
            {% for error in form.dish_type.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}<br>
            Recipes in the category: {{ form.recipes(class_='form-control')}} <br>
            {% for error in form.recipes.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}<br>
            </p>
            <p>{{ form.submit(class_='form-control') }}</p>
            </form>
{% endblock %}

project/templates/add_recipe.html
{% extends "base.html" %}

{% block content %}
    <h1 class='text-center mb-3'>Add A New Recipe</h1>
    <form action="" method="POST" name="add">
        {{form.hidden_tag()}}
        <p>
            Title: {{form.title(class_='form-control')}}<br>
            {% for error in form.title.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}<br>
            Servings: {{form.servings(class_='form-control')}}<br>
            {% for error in form.servings.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}<br>
            Cooking Time: {{form.cooking_time(class_='form-control')}}<br>
            {% for error in form.cooking_time.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}<br>
            Difficulty: {{form.difficulty(class_='form-control')}}<br>
            {% for error in form.difficulty.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}<br>
            Calories: {{form.calories(class_='form-control')}}<br>
            {% for error in form.calories.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}<br>
            Ingredients: {{form.ingredients(class_='form-control')}}<br>
            {% for error in form.ingredients.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}<br>
            Preparation Method: {{form.method(class_='form-control')}}<br>
            {% for error in form.method.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}<br>
            User: {{form.user(class_='form-control')}}<br>
            {% for error in form.user.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}<br>
            Categories: {{form.categories(class_='form-control')}}<br>
            {% for error in form.categories.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}<br>
        </p>
        <p>{{ form.submit(class_='form-control') }}</p>
    </form>

{% endblock %}

project/templates/all_recipes.html
{% extends "base.html" %}
{% block content %}
<h1 class='text-center mb-3'>All Recipes</h1>
<table class="table">
    <thread>
        <tr>
            <th>Title</th>
            <th>Servings</th>
            <th>Time</th>
            <th>Difficulty</th>
            <th>Calories</th>
            <th>Ingredients</th>
            <th>Preparation</th>
            <th>Categories</th>
            <th></th>
        </tr>
    </thread>
    <tbody>
        {% for recipe in recipes %}
        <tr>
            <td>{{recipe.title}}</td>
            <td>{{recipe.servings}}</td>
            <td>{{recipe.cooking_time}}</td>
            <td>{{recipe.difficulty}}</td>
            <td>{{recipe.calories}}</td>
            <td>{{recipe.ingredients}}</td>
            <td>{{recipe.method}}</td>
            <td>{{recipe.categories}}</td>  
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

project/templates/base.html
<!DOCTYPE html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<html lang="en" class="h-100">
    <head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="/static/style.css">
    {% if title %}
    <title>Recipe diary - {{ title }}</title>
    {% else %}
    <title>Recipe diary</title>
    {% endif %}
    <style>
      ul#menu li {
        display: inline;
      }
    </style>
               
    </head>
    <body class="h-100">
      <nav class="navbar navbar-inverse">
      <div class="container-fluid">
      <ul class="nav navbar-nav">
        {% if current_user.is_authenticated %}
        <li><a href="{{url_for('recipes.index')}}">Home</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Recipes
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{{url_for('recipes.allRecipes')}}">All Recipes</a></li>
            <li><a href="{{url_for('recipes.add')}}">Add Recipe</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Categories
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{{url_for('recipes.categories')}}">All Categories</a></li>
            <li><a href="{{url_for('recipes.addCategory')}}">Add Category</a></li>
          </ul>
        </li>
        <li><a href="{{url_for('users.profile')}}">My Profile</a></li>
        <li><a href="{{url_for('users.logout')}}">Logout</a></li>
        {% else %}
        <li><a href="{{url_for('recipes.index')}}">Home</a></li>
        <li><a href="{{url_for('users.login')}}">Login</a></li>
        <li><a href="{{url_for('users.sign_up')}}">SignUp</a></li>
        {% endif %}
      </ul> 
      </div>
    </nav>
        <div class="container-fluid">
            <div class="row">
              <div class="col-md-3"></div>
              <div class="col-md-6">
                {% with messages = get_flashed_messages(with_categories=true) %}
                  {% if messages %}
                  {% for category, message in messages %}
                  <div class="alert alert-{{ category }}" role="alert">
                      <span>{{ message }}</span>
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                      </button>
                  </div>
                  {% endfor %}
                  {% endif %}
                {% endwith %} 
                {% block content %}{% endblock %}
              </div>
              <div class="col-md-3"></div>
            </div>
          </div>
    </body>
</html>

project/templates/categories.html
{% extends "base.html" %}
{% block content %}


<table class="table">
    <thead>
      <tr>
        <th>Categories</th>
        <th></th>
      </tr>
    </thead>
    <tbody>

    {% for c in categories %}
    <tr>
      <td>{{c}}</td>
      <td><a href="/categories/{{c.id}}"><button type="button" class="btn btn-primary">Recipes</button></a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

project/templates/change_password.html
{% extends "base.html" %}

{% block content %}
    <h1 class='text-center mb-3'>Reset Your Password</h1>
    <form action="" method="POST">
        {{form.hidden_tag() }}
        <p>
            New Password: {{ form.password(class_='form-control')}} <br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}<br>
            Confirm new password: {{ form.confirm(class_='form-control')}}<br>
            {% for error in form.confirm.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}<br>
        </p>
        <p>{{ form.submit(class_='form-control') }}</p>
    </form>
{% endblock %}

project/templates/home.html
{% extends "base.html" %}

{% block content %}
<h1 class='text-center mb-3'>Recipe Diary</h1>
<!-- Carousel with recipes(+images) -->
<style>
    .carousel-inner >.item > img,
    .carousel-inner >.item > a > img{
        width:70%;
        margin:auto;
    }

</style>
<div class="container">
<div id="demo" class="carousel slide" data-ride="carousel">

    <!-- Indicators -->
    <ul class="carousel-indicators">
      <li data-target="#demo" data-slide-to="0" class="active"></li>
      <li data-target="#demo" data-slide-to="1"></li>
      <li data-target="#demo" data-slide-to="2"></li>
      <li data-target="#demo" data-slide-to="3"></li>
      <li data-target="#demo" data-slide-to="4"></li>
      <li data-target="#demo" data-slide-to="5"></li>
    </ul>
  
    <!-- The slideshow -->
    <div class="carousel-inner">
      <div class="item active">
        <img class="d-block" src="static/images/active.jpg" alt="Breakfast bowl" style="width:100%;">
      </div>
      <div class="item">
        <img class="d-block" src="static/images/cake.jpg" alt="Apple cake" style="width:100%;">
      </div>
      <div class="item">
        <img class="d-block" src="static/images/falafels.jpg" alt="Falafels" style="width:100%;" >
      </div>
      <div class="item">
        <img class="d-block" src="static/images/honeycookies.jpg" alt="Honey Cookies" style="width:100%;" >
      </div>
      <div class="item">
        <img class="d-block" src="static/images/oats.jpg" alt="Oats" style="width:100%;" >
      </div>
      <div class="item">
        <img class="d-block" src="static/images/pudding.jpg" alt="Chocolate Pudding" style="width:100%;" >
      </div>
    </div>
  
    <!-- Left and right controls -->
    <a class="left carousel-control" href="#demo" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#demo" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
      </a>
</div>
</div>

{% if current_user.is_authenticated %}
<!-- View all recipes and add a recipe if user is authenticated -->
<div class="col-sm-8 col-sm-offset-3 pt-1" style="padding-top: 20px; ">
<a href="{{url_for('recipes.allRecipes')}}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">View all recipes</a>
<a href="{{url_for('recipes.add')}}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Add a new recipe</a>
</div>
{% else %}
<!-- Sing up if user is not authenticated -->
<div class="col-sm-8 col-sm-offset-3 pt-1" style="padding-top: 20px; ">
<a href="{{url_for('users.sign_up')}}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Sign Up Now</a>
</div>
{% endif %}

{% endblock %}

project/templates/login.html
<!-- extend base layoout -->
{% extends "base.html" %}

{% block content %}

    <h1 class='text-center mb-3'>Login</h1>
            <form action="" method="POST" name="signup">
            {{form.hidden_tag() }}
            <p>
            Email: {{ form.email(class_='form-control')}}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}<br>
            Password: {{ form.password(class_='form-control')}} <br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}<br>
            </p>
            <p>{{ form.submit(class_='form-control') }}</p>
            </form>
            <p>
                Forgot Your Password?
                <a href="{{ url_for('users.reset_password_req') }}">Click Here To Reset It</a>
            </p>
{% endblock %}

project/templates/reset_password.html
{% extends "base.html" %}

{% block content %}
    <h1 class='text-center mb-3'>Reset Your Password</h1>
    <form action="" method="POST">
        {{form.hidden_tag() }}
        <p>
            Password: {{ form.password(class_='form-control')}} <br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}<br>
            Confirm password: {{ form.confirm(class_='form-control')}}<br>
            {% for error in form.confirm.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}<br>
        </p>
        <p>{{ form.submit(class_='form-control') }}</p>
    </form>
{% endblock %}

project/templates/reset_password_req.html
{% extends "base.html" %}

{% block content %}
    <h1 class='text-center mb-3'>Reset Your Password</h1>
    <form action="" method="POST">
        {{form.hidden_tag() }}
        <p>
        Email: {{ form.email(class_='form-control')}}<br>
        {% for error in form.email.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}<br>
        </p>
        <p>{{ form.submit(class_='form-control') }}</p>
    </form>
{% endblock %}

project/templates/sign_up.html
<!-- extend base layoout -->
{% extends "base.html" %}

{% block content %}
    <h1 class='text-center mb-3'>Sign up</h1>
<!-- <div class="container h-100">
    <div class="jusify-content-center align-items-center">
        <div class="col-10 col-md-8 col-lg-6"> -->
            <form action="" method="POST" name="signup">
            {{form.hidden_tag() }}
            <p>
            First name: {{form.firstname(class_='form-control')}}<br>
            {% for error in form.firstname.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}<br>
            Surname: {{ form.surname(class_='form-control')}} <br>
            {% for error in form.surname.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}<br>
            Email: {{ form.email(class_='form-control')}}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}<br>
            Password: {{ form.password(class_='form-control')}} <br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}<br>
            Confirm password: {{ form.confirm(class_='form-control')}}<br>
            {% for error in form.confirm.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}<br>
            </p>
            <p>{{ form.submit(class_='form-control') }}</p>
        <!-- <input type="submit" class="btn btn-default" value="Sign Up"> -->
            </form>
        <!-- </div>
    </div>
</div> -->
{% endblock %}

project/templates/user_profile.html
{% extends "base.html" %}
{% block content %}

<div class="user-profile">
    <div class="page-header">
        <h2 class='text-center mb-3'>My Profile</h2>
    </div>

    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <div class="panel panel-primary">
              <div class="panel-heading">User</div>  
              <div class="panel-body">
                {{current_user.firstname}}
                {{current_user.surname}}
            </div>
            </div>
            <div class="panel panel-info">
                <div class="panel-heading">Email</div>  
                <div class="panel-body">{{current_user.email}}</div>
            </div>
            <div class="panel panel-info">
                <div class="panel-heading">My Recipes</div>  
                <div class="panel-body">{{current_user.recipes}}</div>
            </div>
            <div class="panel panel-info">
            <div class="panel-body">
            <a href="{{url_for('users.change_password')}}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Change Password</a>
            </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}